docker name test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -16,18 +16,18 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Verify tag is on main
-        run: |
-          TAG_COMMIT=$(git rev-parse HEAD)
-          MAIN_COMMIT=$(git rev-parse origin/main)
+      # - name: Verify tag is on main
+      #   run: |
+      #     TAG_COMMIT=$(git rev-parse HEAD)
+      #     MAIN_COMMIT=$(git rev-parse origin/main)
 
-          echo "🔖 Tag commit:  $TAG_COMMIT"
-          echo "🌿 Main commit: $MAIN_COMMIT"
+      #     echo "🔖 Tag commit:  $TAG_COMMIT"
+      #     echo "🌿 Main commit: $MAIN_COMMIT"
 
-          if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
-            echo "❌ Tag is not pointing to latest main commit. Aborting release."
-            exit 1
-          fi
+      #     if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
+      #       echo "❌ Tag is not pointing to latest main commit. Aborting release."
+      #       exit 1
+      #     fi
 
       - name: Set up Git
         run: |
